### ISSUE TITLE
WebExtensions: Lack accesskey in context menu item

### ISSUE THREAD

**Issue by asamuzaK** [asamuzaK/withExEditor#18]
Depends on [1320462 – WebExtensions: Add ability to set access key to context menu item](https://bugzilla.mozilla.org/show_bug.cgi?id=1320462)

**Comment by asamuzaK** [comment]
Access key in context menu item is implemented in Blink.

**Comment by JontAlle** [comment]
Hi. I'm not sure I'm in the right place, but here is what I'm up to, and my issue:
I was using "its all text" with mozilla. I understand I need to upgrade to withExEditor.
I was able to install node v 8.9.0 and do the config.js install, and it seems that withExEditor is working
with Mozilla Firefox. There is a little icon in the upper right that brings up an option menu.

Now I would like to use it to edit a wiki webpage like I did with "its all text"
How do I do that? When I go to the page to edit, and click the "edit" button, nothing happens.
With "its all text" it would download the page to be edited, and bring it up in gvim (or vi).
This is not happening. I have not found a discussion on how one uses withExEditor to edit content.
Please help.
jba

**Comment by asamuzaK** [comment]
Right click on a textarea.
You will see `Edit Text with [your editor]` in context menu.

This issue relates to access keys.
Next time please file a new issue.

**Comment by JontAlle** [comment]
OK, now I know where to comment.
I did right click in the textarea, and nothing happens. Nothing. Obviously I'm doing something wrong.
But what?

**Comment by JontAlle** [comment]
some progress: I right clicked several time with my mouse in the area to be edited, and eventually there
was a menu say "edit text with vim"
Then I clicked on this message, and exactly nothing happened.

So I'm seeing the message "edit text with vim" but its not working. Maybe the problem is with the configuration options?

I still dont know what the "u" command is useful for or when it should be used. That is not explained as best I know.

**Comment by asamuzaK** [comment]
Please file new issue on GitHub.
Thanks

On 2017年12月30日 12:35:19 JST, Jont B Allen <notifications@github.com> wrote:
>OK, now I know where to comment.
>I did right click in the textarea, and nothing happens. Nothing.
>Obviously I'm doing something wrong.
>But what?

-- 
Kazumasa Hasegawa <kazz@asamuzak.jp>

**Comment by JontAlle** [comment]
some progress: I right clicked several time with my mouse in the area to be edited, and eventually there
was a menu say "edit text with vim"
Then I clicked on this message, and exactly nothing happened.

So I'm seeing the message "edit text with vim" but its not working. Maybe the problem is with the configuration options?

I still dont know what the "u" command is useful for or when it should be used. That is not explained as best I know.

**Comment by JontAlle** [comment]
and yet more progress:
I ran the command node setup.js once more and answered the questions differently,
and now it seems to be working. When I right click on a text area, gvim starts and I'm able to edit.

The problem with all this is its complexity, and lack of assurance that it actually works. There are too many places where ti can go worng, with no feed back as to why.

But now it seems to be working. I'll let you know again tomorrow if it really does work.
Thanks for the input. 
Jont

**Comment by asamuzaK** [comment]
As I mentioned before, please write your own issue as a new issue, instead of writing in this thread any more.
You are ruining this thread as an issue tracker.

**Comment by asamuzaK** [comment]
Merged to  #82
