### ISSUE TITLE
Can't input Editor Config Path

### ISSUE THREAD

**Issue by ErikKrause** [asamuzaK/withExEditor#45]
Hello,

I can't input Editor Config Path. Any time I input it and close the configuration page it gets deleted. This is v 3.4.0 on Firefox 57.0b14 (64-Bit) Path is C:\MeineProgramme\ExWith\config\firefox\editorconfig.json

**Comment by asamuzaK** [comment]
Please run the setup script on the host again and enter your editor path.

As I plan to release version 4 shortly, I will make this issue a wontfix.
Sorry for that.

**Comment by asamuzaK** [comment]
Released v4.0.0
[withExEditor - Add-ons for Firefox](https://addons.mozilla.org/en-US/firefox/addon/withexeditor/ "withExEditor - Add-ons for Firefox")

Editor related settings are removed from the options page because of security concerns.
See [Editor configuration trusts the browser side too much · Issue #15 · asamuzaK/withExEditorHost](https://github.com/asamuzaK/withExEditorHost/issues/15 "Editor configuration trusts the browser side too much · Issue #15 · asamuzaK/withExEditorHost")

**Comment by ErikKrause** [comment]
Accepted :-) 
Wouldn't it be possible to use the settings under view_source.editor in about:config to configure the editor?

**Comment by asamuzaK** [comment]
Unfortunately, there's no way to get values of about:config in WebExtensions.

**Comment by ErikKrause** [comment]
Not even a system call to have Firefox opening the file?
