### ISSUE TITLE
TEXTBOX not handled

### ISSUE THREAD

**Issue by edelhauge** [asamuzaK/withExEditor#50]
I'm here because I'm trying to replace Its All Text with withExEditor.

I installed everything and can View Page Source with my editor.

I was not able to edit the text element in my Wiki, but then I found that I was able to edit the search box in the Google home page.

The difference is that Google uses an INPUT field and I use a TEXTBOX field.

Any work around or fix I can expect?

-- Ed Elhauge

**Comment by edelhauge** [comment]
I thought I'd add that my Environment is:
  * Apple macOS Sierra,
  * Firefox 57, and
  * Vim.app as the editor.

-- Ed Elhauge

**Comment by asamuzaK** [comment]
> I was not able to edit the text element in my Wiki

What do you mean "not able to edit"?
* context menu "Edit Text with ..." doesn't appear?
* context menu "Edit Text with ..."  appears but is grayed out?
* clicked "Edit Text with ..."  but editor did not execute?
* something else?

Also, check if there is any error in web console (Ctrl + Shift + k) and browser console (Ctrl + Shift + J)

**Comment by Eli-the-Bearded** [comment]
I'm having what I think is the same issue. "something else" is the appropriate answer, and I see no errors in web console or browser console.

FF57 on Linux, fresh install today of withExEditor and withExEditorHost (and fresh install of node, since my previously installed version was too old).

Steps to reproduce:

1. Go to my textarea test page: http://qaz.wtf/ta/
2. Type some text
3. Select text
4. Use context menu to "Edit with ..."

(Steps two and three might not be needed.)

What happens:

My editor opens up, with the source code of the page. Editing that text, then saving and quitting does not in anyway change the contents of the textarea.

What was expected:

My editor opens up, with the contents of the textarea. Editing that text, then saving and quitting would replace the contents of the textarea.

(Additionally, the source code in the editor is a fresh download of the page, not the version in the browser. I confirmed this by editing the test page between loading in Firefox and using withExEditor.)

**Comment by asamuzaK** [comment]
@Eli-the-Bearded 

Confirmed the issue.
Thanks for the test case.

And I think I know why this happens.
It's maybe because there is no ID attribute in textarea or it's ancestor.
To make sure it is the real cause, will you add an id to form element and try it again?

**Comment by Eli-the-Bearded** [comment]
Can confirm: adding an ID to the textarea fixes the issue.

**Comment by asamuzaK** [comment]
Thanks.
I'll fix this.

**Comment by asamuzaK** [comment]
@Eli-the-Bearded 

Will you put your test case without any ID for a while?
I want to check with it during fixing this issue.
Thanks.

**Comment by Eli-the-Bearded** [comment]
Done. (No more response from me tonight, though, I'm going to bed.)

**Comment by asamuzaK** [comment]
Thanks, and good night.

**Comment by asamuzaK** [comment]
Fixed.
Try build.
[withExEditor v4.0.2a1](https://addons.mozilla.org/en-US/firefox/addon/withexeditor/versions/beta "withExEditor :: Versions :: Firefox 向けアドオン")

@edelhauge 
Is your issue the same?

**Comment by Eli-the-Bearded** [comment]
4.0.2a1 fixes this for me. 🎉

**Comment by edelhauge** [comment]
Hi Kazz,

Thanks for the info. I can confirm the most important info; my problem went away when I added an ID="IDNUM" to each of my TEXTAREAs.

I'll also fill in what I left out in my original post. When I said "not able to edit" I was vague. I was able to click "View Page Source with vim", and got the full HTML text of the page, in vim. When I clicked in an editable field, I was able to click "Edit Text with vim", and vim was started, but it contained the page HTML, not the text in the editable field; when you quit the editor, you didn't get a field update.

Now, with IDs added, that "Edit Text with vim" cycle work correctly.

I would add one aside. I've been using "It's All Text" for years now, and there is one feature it has you might consider. After you quit the editor, It's All Text synchronizes the field, and then flashes the field in yellow for a few seconds. That comes in handy because if you have a large amount of text in a field, it might take a few seconds to resync, and if you click on a "Save Changes" button too soon, you might be saving the old text, not the new, edited text.

Cheers, Ed

**Comment by asamuzaK** [comment]
Thanks for testing.

> flashes the field in yellow for a few seconds

To do that, it needs to insert CSS to the web page, which also raises a risk of finger printing.

**Comment by asamuzaK** [comment]
Released [withExEditor v4.0.2](https://addons.mozilla.org/en-US/firefox/addon/withexeditor/ "withExEditor – Firefox 向けアドオン")
Note that beta versions will not update to release versions, so you need to update yourself.

**Comment by HairyDude** [comment]
Seems to have regressed in 4.1.1. "Edit text" in a textarea opens the page source.
