### ISSUE TITLE
Tips for using with Mailvelope?

### ISSUE THREAD

**Issue by benyakov** [asamuzaK/withExEditor#97]
I'd like to use Mailvelope for PGP in Gmail. It provides an alternative message
editing interface with a real text box. This pops up in Firefox as a separate
window frame.  For some reason, the WithExEditor menu item is disabled, and the
editor keystroke does not work. In the past I was able to use WithExEditor for
this text, but not now.

Any ideas?

**Comment by asamuzaK** [comment]
I'll take a look.

**Comment by asamuzaK** [comment]
>  In the past I was able to use WithExEditor for
this text

Please tell me in which version of Firefox and/or which version of withExEditor was able to use?

**Comment by benyakov** [comment]
Sorry, I haven't kept track of the versions as they changed. It has been a
long time since it worked. Maybe even a year.

**Comment by asamuzaK** [comment]
I see.

In WebExtensions (the current add-on ecosystem), add-ons can not run inside other add-ons.
Instead, it is designed to exchange messages between add-ons.

That is, in order to exchange messages, it is necessary to modify not only the withExEditor side but also the Mailvelope side.

Please contact Mailvelope's developer and ask if there is a chance to implement an API to exchange messages with other add-ons.
If they say yes, let's go further then.

But, considering the purpose of Mailvelope, I personally have an impression that the possibility of allowing external editor is unlikely to be high, though.

**Comment by asamuzaK** [comment]
See [Message Exchange with Other Add-ons? · Issue #612 · mailvelope/mailvelope](https://github.com/mailvelope/mailvelope/issues/612)

**Comment by asamuzaK** [comment]
There seems to be no progress on the mailvelope side, so close the issue at the moment.
Feel free to reopen.
